### ISSUE TITLE
Když máš na stránce hodně fotek, tek je dobré je latyloadovat.

### ISSUE THREAD

**Issue by DNepovim** [J1939G/pittsburg#2]
Pokud nechceš používat nějakou knihovnu, tak ti pomůže [Intersection Observe API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API), potřebuješ ale po [polyfill](https://github.com/w3c/IntersectionObserver/tree/master/polyfill).

https://www.vzhurudolu.cz/prirucka/intersection-observer

**Comment by J1939G** [comment]
Je to dobré, ale mám dvě důvody, proč to použivat nebudu. Jednak u většiny obrázků nemám pevně nastavenou vyšku, takže na začatku vlastně všechny (prázdné) obrázky jsou uvnitř `viewport`u, čímž je `lazyload`ing vlastně nanic, a zadruhé na žádné stránce nebudou víc jak 3 zakryté fotky. Jinak se `srcset`em už se stránky načtou mnohonásobně rychleji.
